##Arquivo de configuração dos Containeres Docker.

##Configuração do container da Aplicação Web.
version: '3'
services: 
  web:
    restart: always
    build: .
    volumes: 
      - ./:/var/www/
    depends_on: 
      - db

#Configuração do container do banco de dados PostgreSQL
  db:
    image: postgres:12.0-alpine
    container_name: ${DB_HOST}
    restart: always
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD} 
      POSTGRES_DB: ${DB_DATABASE}
    volumes: 
    - "./.docker/dbdata:/var/lib/postgresql/data"

#Configuração do container de servidor Web Nginx 
  nginx:
    build: ./.docker/nginx
    restart: always
    ports:
      - "8000:80"
    volumes: 
      - ./:/var/www
    depends_on: 
      - web

#Configuração do SGBD PostgreSQL PGAdmin
  teste-pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "victorrayansouzaramos@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "pgadmin123"
    ports:
      - "16543:80"
    depends_on:
      - db
    #networks:
    #  - ${DB_HOST}